Add ability to install python
* Also include an initial-env file that can be sources to set
  environment variables

diff --git a/bin/pyenv-installer b/bin/pyenv-installer
--- a/bin/pyenv-installer
+++ b/bin/pyenv-installer
@@ -27,9 +27,13 @@
 #   of, or 'system' which will detect the current version of python the system
 #   has and install that with pyenv.
 #
-# WORKON_HOME="${HOME}/.virtualenvs"
+# WORKON_HOME="$HOME/.virtualenvs"
 #   Where virtualenvs live. Again suggest "${XDG_DATA_HOME}/virtualenvs" to
-#   keep home directory clean.
+#   keep home directory clean. If not set then default is $HOME/.virtualenvs
+#
+# PROJECT_HOME=
+#   Used by virtualenvwrapper when creating a new project. If defined it will be
+#   added to profile.
 
 set -e
 [ -n "$PYENV_DEBUG" ] && set -x
@@ -38,12 +42,29 @@ if [ -z "$PYENV_ROOT" ]; then
   PYENV_ROOT="${HOME}/.pyenv"
 fi
 
+if [ -z "$WORKON_HOME" ]; then
+  WORKON_HOME="${HOME}/.virtualenvs"
+fi
+
 if [ -z "$PYENV_INITIAL_VERSION" ]; then
   PYENV_INITIAL_VERSION='none'
 elif [ "$PYENV_INITIAL_VERSION" == "system" ]; then
   system_python="$(python -V 2>&1)"
   PYENV_INITIAL_VERSION="${system_python##* }"
 fi
+
+{ echo
+  echo "Proceeding with the following settings in 5 seconds"
+  echo "Press control-c to cancel and make changes"
+  echo
+  echo "PYENV_ROOT: $PYENV_ROOT"
+  echo "WORKON_HOME: $WORKON_HOME"
+  echo "PYENV_SKIP_UPDATE: ${PYENV_SKIP_UPDATE:-(blank)}"
+  echo "PYENV_INITIAL_VERSION: $PYENV_INITIAL_VERSION"
+  echo
+} >&2
+
+sleep 5
 
 if [ -z "$PYENV_SKIP_UPDATE" ]; then
   if [ -f '/etc/os-release' ] && \
@@ -73,6 +94,11 @@ checkout() {
   [ -d "$2" ] || git clone "$1" "$2"
 }
 
+# Changes "/home/foo/whatever" to "$HOME/whatever"
+filter_home() {
+  echo "$1" | sed -e "s,$HOME,\$HOME,"
+}
+
 if ! command -v git 1>/dev/null 2>&1; then
   echo "pyenv: Git is not installed, can't continue." >&2
   exit 1
@@ -95,7 +121,7 @@ if ! command -v pyenv 1>/dev/null; then
 
   case "$shell" in
   bash )
-    profile="~/.bash_profile"
+    profile="$HOME/.bash_profile"
     ;;
   zsh )
     profile="~/.zshrc"
@@ -111,26 +137,64 @@ if ! command -v pyenv 1>/dev/null; then
     ;;
   esac
 
-  loadpath="$(echo "${PYENV_ROOT}" | sed -e "s,$HOME,\$HOME,")"
+  pyenv_path="$(filter_home "${PYENV_ROOT}")"
+  workon_home_path="$(filter_home "${WORKON_HOME}")"
+  project_home_path="$(filter_home "${PROJECT_HOME:-$HOME/code}")"
 
   { echo "# Load pyenv automatically by adding"
-    echo "# the following to ${profile}:"
+    echo "# the following to $(filter_home "${profile}"):"
+    echo "# if you set PYENV_INITIAL_VERSION this is done for you"
     echo
     case "$shell" in
     fish )
-      echo "set -x PATH \"${loadpath}/bin\" \$PATH"
+      echo "set -x PATH \"${pyenv_path}/bin\" \$PATH"
       echo 'status --is-interactive; and . (pyenv init -|psub)'
       ;;
     * )
-      echo "export PATH=\"${loadpath}/bin:\$PATH\""
-      echo "export WORKON_HOME=\"\$HOME/.local/share/virtualenvs\""
-      echo "export PROJECT_HOME=\"\$HOME/code\""
+      echo "export PYENV_ROOT=\"${pyenv_path}\""
+      echo "export PATH=\"\$PYENV_ROOT/bin:\$PATH\""
+      echo "export WORKON_HOME=\"${workon_home_path}\""
+      echo "export PROJECT_HOME=\"${project_home_path}\" #this one is optional"
       echo "eval \"\$(pyenv init -)\""
+      echo
       ;;
     esac
-    echo
+  } >&2
+
+  if [ "$PYENV_INITIAL_VERSION" != 'none' ]; then
+    if [ "$shell" != 'bash' ]; then
+      echo "Setting up initial version only supports bash shells currently" >&2
+      exit 1
+    fi
+
+    echo >>"${profile}"
+    echo "export PYENV_ROOT=\"${pyenv_path}\"" >>"${profile}"
+    echo "export PATH=\"\$PYENV_ROOT/bin:\$PATH\"" >>"${profile}"
+    echo "export WORKON_HOME=\"${workon_home_path}\"" >>"${profile}"
+    if [ -n $PROJECT_HOME ]; then
+      echo "export PROJECT_HOME=\"$(filter_home "${PROJECT_HOME}")\"" >>"${profile}"
+    fi
+    echo "eval \"\$(pyenv init -)\"" >>"${profile}"
+    source "${profile}"
+    if [ $(command -V pyenv &>/dev/null; echo $?) -ne 0 ]; then
+      echo "pyenv still doesn't exist, aborting install" >&2
+      exit 1
+    fi
+  fi
+fi   # end if pyenv not found
+
+if [ "$PYENV_INITIAL_VERSION" != 'none' ]; then
+  pyenv install $PYENV_INITIAL_VERSION
+  pyenv global $PYENV_INITIAL_VERSION
+  pyenv virtualenvwrapper
+  echo "pyenv virtualenvwrapper" >>"${profile}"
+  echo >&2
+  echo "finished setting up virtualenvwrapper" >&2
+  echo 'relogin or `source ~/.bash_profile` to get started' >&2
+else
+  { echo
     echo "# There's some post install steps for virtualenvwrapper. Do above"
-    echo "# commands or source ${profile} then run the following"
+    echo "# commands or source ${profile} if needed then run the following"
     echo
     echo "pyenv install 2.7.8"
     echo "pyenv global 2.7.8"
@@ -142,3 +206,8 @@ if ! command -v pyenv 1>/dev/null; then
     echo
   } >&2
 fi
+
+echo >&2
+echo "Finished install: Have a nice day!" >&2
+
+exit 0
